# ==============================================================================
# PAPER WORLD DEFAULTS TEMPLATE (Ultra-Safe Autosave & Anti-Lag)
# Preserva integridade de blocos, entidades, animais domados e chunks
# ==============================================================================
_version: 30

chunks:
  auto-save-interval: 400 # Salva chunks a cada 20 segundos para evitar qualquer rollback
  delay-chunk-unloads-by: 10s
  entity-per-chunk-save-limit:
    arrow: 16
    experience_orb: 16
    ender_pearl: 8
    snowball: 16
  fixed-chunk-inhabited-time: -1
  flush-regions-on-save: true # Gravação forçada em disco imediatamente
  max-auto-save-chunks-per-tick: 24
  prevent-moving-into-unloaded-chunks: true

entities:
  armor-stands:
    do-collision-entity-lookups: false
    tick: false
  behavior:
    disable-chest-cat-detection: true
    spawner-nerfed-mobs-should-jump: false
  spawning:
    despawn-ranges:
      ambient:
        hard: 72
        soft: 32
      axolotls:
        hard: 72
        soft: 32
      creature:
        hard: 128
        soft: 32
      misc:
        hard: 72
        soft: 32
      monster:
        hard: 128
        soft: 36
      underground_water_creature:
        hard: 72
        soft: 32
      water_ambient:
        hard: 56
        soft: 32
      water_creature:
        hard: 72
        soft: 32
    non-tick-mobs-despawn-speed: 20

collisions:
  allow-player-cramming-damage: true
  fix-climbing-bypassing-cramming-rule: true
  max-entity-collisions: 4

environment:
  optimize-explosions: true
  treasure-maps:
    enabled: true
    find-already-discovered:
      loot-tables: true
      villager-trade: true

tick-rates:
  sensor:
    villager:
      secondarypoisensor: 40
  behavior:
    villager:
      validatenearbypoi: 40
      acquirepoi: 120
